spring:
  datasource:
    url: jdbc:h2:mem:testdb
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${email}
    password: ${emailPassword}
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
          starttls:
            enable: true
        transport:
          protocol: smtp
    protocol: smtp

paystack:
  secret_key: ${paystackKey}
