spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/shortlet
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: shortlet.sql


  mail:
    host: smtp.gmail.com
    port: 465
    username: ${email}
    password: ${emailPassword}
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
          starttls:
            enable: true
        transport:
          protocol: smtp
    protocol: smtp


paystack:
  secret_key: ${paystackKey}
elasticsearch:
  url: localhost:9200
