spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:shortlet}
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: shortlet.sql


  mail:
    host: smtp.gmail.com
    port: 465
    username: ghostpythoncode@gmail.com
    password: guoepbikitnhatts
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
          starttls:
            enable: true
        transport:
          protocol: smtp
    protocol: smtp


paystack:
  secret_key: "sk_test_5979e6e7cb563c31f743171f14ad25abb6ea43a4"
elasticsearch:
  url: localhost:9200
